### ISSUE TITLE
Registration not possible

### ISSUE THREAD

**Issue by Sagre** [ultical/ultical#80]
Tried to view the team roster at this page:
https://www.dfv-turniere.de/de/deutsche-meisterschaft-nord-west-indoor-5-liga-mixed-2017--3137

Pressed registrate, filled in my information (can provide it per mail) hit registrate and nothing happened

**Comment by Sagre** [comment]
Using google chrome Version 62.0.3202.89 (Offizieller Build) (64-Bit)

**Comment by bslbckr** [comment]
There is a strong requirement from DFV that dfv-turniere.de has to be restricted to people being DFV-members. Therefore you  have to provide your personal data. However, as you don't receive an error message I conclude for the moment, that a matching entry in the DFV's database exists and has been found. 

The next step is to send an confirmation email to your email address, that is registered with the DFV. Have you checked this address?

**Comment by Sagre** [comment]
Well, I got no Feedback from the site whatsoever. I am a registred dfv member, under the same email as i tried using to Register myself.
Also i got now email, even in my spam Folder.

So it would be nice to know what went wrong.

Von: Basil
Gesendet: Dienstag, 7. November 2017 17:00
An: ultical/ultical
Cc: Sagre; Author
Betreff: Re: [ultical/ultical] Registration not possible (#80)

There is a strong requirement from DFV that dfv-turniere.de has to be restricted to people being DFV-members. Therefore you have to provide your personal data. However, as you don't receive an error message I conclude for the moment, that a matching entry in the DFV's database exists and has been found.
The next step is to send an confirmation email to your email address, that is registered with the DFV. Have you checked this address?

**Comment by bslbckr** [comment]
I totally agree :smile: 

From what I can see in the database, no mail has been sent out to you, as I don't find a mail confirmation code, having today's date. Hence @bastrapp has to have a look into the log-files.

**Comment by Sagre** [comment]
Alright. Let me now if you Need more Information from me 😊

Von: Basil
Gesendet: Dienstag, 7. November 2017 17:16
An: ultical/ultical
Cc: Sagre; Author
Betreff: Re: [ultical/ultical] Registration not possible (#80)

I totally agree 😄
From what I can see in the database, no mail has been sent out to you, as I don't find a mail confirmation code, having today's date. Hence @bastrapp has to have a look into the log-files.

**Comment by bastrapp** [comment]
Hey. Sorry, i am in vacation until next wednesday. Will look into it
afterwards

Am 07.11.2017 17:19 schrieb "Sagre" <notifications@github.com>:

Alright. Let me now if you Need more Information from me 😊

Von: Basil
Gesendet: Dienstag, 7. November 2017 17:16

An: ultical/ultical
Cc: Sagre; Author
Betreff: Re: [ultical/ultical] Registration not possible (#80)

I totally agree 😄
From what I can see in the database, no mail has been sent out to you, as I
don't find a mail confirmation code, having today's date. Hence @bastrapp
has to have a look into the log-files.
—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ultical/ultical/issues/80#issuecomment-342536069>, or mute
the thread

**Comment by bastrapp** [comment]
Hey Sagre, sorry for my late reply. If you could send me the information you used for signing up to bas@ultical.com I will further investigate ;-)

**Comment by Sagre** [comment]
Hello bas,

no Problem.

I just retried the Registration in order to check what Information were required and the Registration was successfull. So I just assume that your Server had some form of hiccup.

Thank you for your willing to help, though.

Greetings,

Von: bas
Gesendet: Mittwoch, 22. November 2017 11:24
An: ultical/ultical
Cc: Sagre; Author
Betreff: Re: [ultical/ultical] Registration not possible (#80)

Hey Sagre, sorry for my late reply. If you could send me the information you used for signing up to bas@ultical.com I will further investigate ;-)

**Comment by bslbckr** [comment]
I think it's ok to close this issue. @bastrapp  if you notice anything strange in the log-files we should consider opening a separate issue.
